#!/bin/sh

while [ -z "$TITLE" ]; do
  read "Enter post title: " TITLE
  echo
done

CLEAN_TITLE="$(echo "$TITLE" | sed 's/./\L&/g; \
s/[^a-z0-9 -]/_/g; \
s/ /_/g; \
s/_\+/_/g; \
s/^_\+//; \
s/_\+$//;')"

FILENAME="pages/posts/${CLEAN_TITLE}.html"

if [ -f "$FILENAME" ]; then
  read "Post \"$TITLE\" already exists; overwrite it? [y/N] " OVERWRITE
  echo

  case $OVERWRITE in
    [Yy]* ) ;;
    * ) exit 0 ;;
  esac
fi

echo "<h2>$(./encode_text "$TITLE")</h2>" > "$FILENAME"

read "Post \"$TITLE\" created, edit post? [Y/n] " EDIT_CONFIRM
echo

case $EDIT_CONFIRM in
  [Nn]* ) exit 0 ;;
  * )
    if [ -z "$EDITOR" ]; then
      [ -z "$VISUAL" ] && EDITOR='vim' || EDITOR="$VISUAL"
    fi

    exec $EDITOR "$FILENAME" -c '$'
    ;;

esac

