#!/bin/sh

BASE_URL='https://example.com'

create_page() {
  TITLE="$(head -n 1 $1 | sed 's/<\/\?h2>//g')"
  ./unsafe_gen_page "$1" "templates/base_production.html" "$TITLE"
}

add_to_blog() {
  NAME="$(basename $1)"
  DIR="$(dirname $1 | sed 's/^pages\/\?//')"
  [ -z "$DIR" ] && FILENAME="$NAME" || FILENAME="$DIR/$NAME"

  HEADER="$(date +"%B %Y")"
  DATE="$(date +"%Y %b %d")"
  TITLE="$(head -n 1 $1 | sed 's/<\/\?h2>//g')"

  RAMTMP=$(mktemp)

  if [ -z "$(grep "<h2>$HEADER</h2>" pages/blog.html)" ]; then
    echo "<h2>$HEADER</h2>
<ul>
	<!-- $HEADER -->
</ul>" > $RAMTMP
    sed -i "/<!-- wt -->/r $RAMTMP" pages/blog.html
  fi
  
  echo "	<li>$DATE - <a href="'"'"/$(echo "$FILENAME" |
    sed 's/\.html$//g')\">$TITLE</a></li>" > $RAMTMP

  sed -i "/<!-- $HEADER -->/r $RAMTMP" pages/blog.html

  rm $RAMTMP

  ./unsafe_gen_page \
    "pages/blog.html" "templates/base_production.html" "Blog"

  return 0
}

insert_tag() {
  # tag_name description indents new_line

  TAB='  '
  ADD_TAB="$(for i in {0..$(($3 + 1))}; do printf "$TAB"; done)"

  [ "$4" -eq 1 ] &&
    LINE="<$1>\n$(echo "$2" | awk "$(./add_tabs "$TAB")")\n</$1>" ||
    LINE="<$1>$2</$1>"

  echo "$LINE" | awk "$(./add_tabs "$TAB")"
}

add_to_rss() {
  NAME="$(basename $1)"
  DIR="$(dirname $1 | sed 's/^pages\/\?//')"
  [ -z "$DIR" ] && FILENAME="$NAME" || FILENAME="$DIR/$NAME"

  TITLE="$(head -n 1 $1 | sed 's/<\/\?h2>//g')"
  URL="$BASE_URL/$(echo "$FILENAME" | sed 's/\.html$//g')"
  DATE="$(date +'%a, %d %b %Y %H:%M:%S %z')"
  DESCRIPTION="<![CDATA[
$(tail -n+2 $1 | awk "$(./add_tabs '  ')" | sed '/^ *$/d')
]]>"

  RAMTMP="$(mktemp)"

  echo "$(insert_tag "item" "$(insert_tag "title" "$TITLE" 0 0)
$(insert_tag "guid" "$URL" 0 1)
$(insert_tag "pubDate" "$DATE" 0 0)
$(insert_tag "description" "$DESCRIPTION" 0 1)" 2 1)" > $RAMTMP

  sed -i "/<!-- wt -->/r $RAMTMP" "production/rss.xml"
  rm $RAMTMP
}

if [ "$#" -eq 0 ]; then
  echo 'Usage: push_post <path to post>'
  
else
  create_page $1

  printf "Update blog? [y/N]: "
  read UPDATE
  echo

  case "$UPDATE" in
    [Yy]*) add_to_blog "$1" && add_to_rss "$1" ;;
    *) ;;
  esac

fi

exit 0

