#!/bin/sh

mkdir pages
mkdir templates
mkdir testing
mkdir production

printf 'Enter a title for your page: '
read TITLE
echo

echo "<!DOCTYPE html>
<html lang=\"en-us\">
	<head>
		<meta charset=\"utf-8\" />
		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>
		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
		<title>$TITLE</title>
		<link rel=\"stylesheet\" href=\"style.css\" />
	</head>
	<body>
		<main>
			<!-- wt -->
		</main>
	</body>
</html>
" > templates/base_testing.html

echo "<!DOCTYPE html>
<html lang=\"en-us\">
	<head>
		<meta charset=\"utf-8\" />
		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>
		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
		<title>$TITLE</title>
		<link rel=\"stylesheet\" href=\"/style.css\" />
	</head>
	<body>
		<main>
			<!-- wt -->
		</main>
	</body>
</html>
" > templates/base_production.html

touch pages/style.css

echo '<!-- base -->
<h1>Welcome to my website!</h1>' > pages/index.html

echo
printf 'Do you want to add a blog now? [y/N] '
read ADD_RSS
echo

case "$ADD_RSS" in
  [Yy]*) echo ''; ./setup_rss ;;
  *) ;;
esac

echo
printf 'Do you want to delete the example folder? [Y/n] '
read DELETE_EXAMPLE
echo

case "$DELETE_EXAMPLE" in
  [Nn]*) ;;
  *) rm -r example/ ;;
esac

echo '
Basic configuration is set up!
Before continuing, make sure you have read README.md to understand how \
this workspace is currently configured and how to modify it.'

exit 0

