#!/bin/sh

mkdir pages/posts
mkdir production/posts

printf 'Enter a title for your blog: '
read TITLE
echo

printf 'Enter a description for your blog: '
read DESCRIPTION
echo

printf 'Enter the domain name for your website: '
read DOMAIN
echo

echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">
  <channel>
    <title>$(echo "$TITLE" |
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&rt;/g; s/"/\&quot;/g')</title>
    <description>
      $(echo "$DESCRIPTION" |
      sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&rt;/g; s/"/\&quot;/g')
    </description>
    <language>en-us</language>
    <link>https://$DOMAIN/rss.xml</link>
    <atom:link href=\"https://$DOMAIN/rss.xml\" rel=\"self\" type=\"application/rss+xml\"/>
    <!-- wt -->
    </channel>
</rss>" > production/rss.xml

sed -i 's/example\.com/'"$DOMAIN"'/g' push_post

echo "<p>You can <a href=\"/rss.xml\">subscribe to this blog</a> by adding the RSS link to your preferred reader.</p>
<!-- wt -->" > pages/blog.html

echo 'Blog system and RSS feed set up!'
exit 0

