#!/bin/sh

NAME="$(basename $1)"
DIR="$(dirname $1 | sed 's/^pages\/\?//')"
[ -z "$DIR" ] && FILE="$NAME" || FILE="$DIR/$NAME"

TAB="$(grep "wt" $2 | sed -e 's/<!-- wt -->.*//')"
[ -z "$(echo "$2" | grep "testing")" ] &&
  FOLDER='production' ||
  FOLDER='testing'

RAMTMP=$(mktemp)
awk "$(./add_tabs "$TAB")" $1 > $RAMTMP

mkdir -p $FOLDER/$DIR
cp $2 $FOLDER/$FILE

sed -i "/<!-- wt -->/r $RAMTMP" $FOLDER/$FILE
sed -i '/<!-- wt -->/d' $FOLDER/$FILE

[ "$#" -ge 3 ] &&
  sed -i "s/<\/title>/ | $3&/" $FOLDER/$FILE

echo "Created page $FOLDER/$FILE"
rm $RAMTMP

