#!/bin/sh
 
run_update() {
  for FILE in $(find "$1" -iname '*.html'); do
    [ ! -z "$(grep '<title>.*|' $FILE)" ] &&
      ./gen_page "$(echo "$FILE" | sed "s/$1/pages/")" "$1" "$(
        sed -n 's/.*<title>.*| \(.*\)<\/title>.*/\1/p;' $FILE)" ||
      ./gen_page "$(echo "$FILE" | sed "s/$1/pages/")" "$1"
  done
}

echo 'OPTIONS:
1 - Refresh testing
2 - Refresh production
3 - Refresh both'

while true; do
  printf "Choose an option: "
  read REF_OPTION
  echo
  
  case $REF_OPTION in
    '1') ;;
    '2') ;;
    '3') ;;
    *) continue ;;
  esac

  break
done

[ "$((REF_OPTION & 1))" -ne 0 ] && run_update 'testing'
[ "$((REF_OPTION & 2))" -ne 0 ] && run_update 'production'

